import Image from 'next/image';
import React from 'react';

import quickStart1 from '@/assets/images/qs-1.png';
import quickStart2 from '@/assets/images/qs-2.png';
import quickStart3 from '@/assets/images/qs-3.png';
import quickStart4 from '@/assets/images/qs-4.png';
import quickStart5 from '@/assets/images/qs-5.png';

const QuickStart = () => {
  return (
    <div className='flex flex-wrap justify-around gap-y-4 p-2 text-center text-lg'>
      <div className='flex max-w-md flex-col items-center gap-x-2'>
        <p className='text-xl text-rs-orange'>Step 1</p>
        <div className='flex items-center border-2 pl-2'>
          <p>
            Search the RuneLite plugin hub for &quot;Collection log&quot; and
            install the plugin
          </p>
          <Image
            src={quickStart1}
            alt='Plugin install image'
            className='h-[200px]'
          />
        </div>
      </div>
      <div className='flex max-w-md flex-col items-center'>
        <p className='text-xl text-rs-orange'>Step 2</p>
        <div className='flex items-center gap-x-2 border-2 pl-2'>
          <p>
            Within the Collection log plugin config, enable &quot;Allow
            collectionlog.net connections&quot;
          </p>
          <Image
            src={quickStart2}
            alt='Plugin install image'
            className='h-[200px]'
          />
        </div>
      </div>
      <div className='flex flex-col items-center'>
        <p className='text-xl text-rs-orange'>Step 3</p>
        <div className='flex max-w-md flex-col items-center gap-y-2 border-2 pt-2'>
          <p>Accept the warning upon enabling the configuration option</p>
          <div className='p-2 text-base'>
            <p className='text-lg text-rs-orange'>Note</p>
            <p>
              Making a network request to any website requires the submission of
              your IP address. collectionlog.net does not store your IP address.
            </p>
            <p>
              The account hash is generated by RuneLite as a unique identifier
              of your account. This hash cannot be used to login to/modify your
              account in any way. This is stored in order to verify the account
              uploading their collection log to collectionlog.net owns that
              data.
            </p>
          </div>
          <Image src={quickStart3} alt='Plugin install image' />
        </div>
      </div>
      <div className='flex max-w-md flex-col items-center'>
        <p className='text-xl text-rs-orange'>Step 4</p>
        <div className='flex items-center gap-x-2 border-2 pl-2'>
          <p>
            Open the collection log in-game and click on all pages marked with
            &quot;*&quot;
          </p>
          <Image
            src={quickStart4}
            alt='Plugin install image'
            className='h-[200px]'
          />
        </div>
      </div>
      <div className='flex max-w-md flex-col items-center'>
        <p className='text-xl text-rs-orange'>Step 5</p>
        <div className='flex items-center gap-x-2 border-2 pl-2'>
          <p>
            In the collection log plugin sidebar under the account tab click
            &quot;Upload collection log&quot; to upload your data to
            collectionlog.net
          </p>
          <Image
            src={quickStart5}
            alt='Plugin install image'
            className='h-[200px]'
          />
        </div>
      </div>
    </div>
  );
};

export default QuickStart;
